---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Вика.
--- DateTime: 27.10.2020 13:06
---

fx_version "cerulean"
games {"gta5"}

client_script 'client.lua'
ui_page 'html/build/index.html'
files {
    'html/build/index.html',
    'html/build/*',
    'html/build/static/js/*',
    'html/build/static/css/*',
    'html/build/static/media/*',
}